Sacliofe:
    type: entity
    table: SACLIOFE
    id:
        numerod:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: NumeroD
        codclie:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: CodClie
    lifecycleCallbacks: {  }
