Saclicnv:
    type: entity
    table: SACLICNV
    id:
        codconv:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: CodConv
        codclie:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: CodClie
    lifecycleCallbacks: {  }
