Sacorrelsis:
    type: entity
    table: SACORRELSIS
    id:
        fieldname:
            type: string
            nullable: false
            length: 20
            fixed: false
            id: true
            column: FieldName
            generator:
                strategy: IDENTITY
    fields:
        codsucu:
            type: string
            nullable: false
            length: 5
            fixed: false
            column: CodSucu
        codesta:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: CodEsta
        valuestr:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: ValueStr
        valueint:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: ValueInt
        valuedec:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: ValueDec
    lifecycleCallbacks: {  }
