Saeopi:
    type: entity
    table: SAEOPI
    id:
        periodo:
            type: string
            nullable: false
            length: 8
            fixed: false
            id: true
            column: Periodo
            generator:
                strategy: IDENTITY
    fields:
        codsucu:
            type: string
            nullable: true
            length: 5
            fixed: false
            column: CodSucu
        mtocargos:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoCargos
        mtodescarg:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoDescarg
        mtotraslad:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoTraslad
        cntcargos:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: CntCargos
        cntdescarg:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: CntDescarg
        cnttraslad:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: CntTraslad
    lifecycleCallbacks: {  }
