Saesrv:
    type: entity
    table: SAESRV
    id:
        codserv:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: CodServ
        periodo:
            type: string
            nullable: false
            length: 6
            fixed: false
            id: true
            column: Periodo
    fields:
        mtoventas:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoVentas
        cntventas:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: CntVentas
        costo:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Costo
        mtocompra:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoCompra
        cntcompra:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: CntCompra
    lifecycleCallbacks: {  }
