Saeven:
    type: entity
    table: SAEVEN
    id:
        codvend:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: CodVend
        periodo:
            type: string
            nullable: false
            length: 6
            fixed: false
            id: true
            column: Periodo
    fields:
        mtoventas:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoVentas
        costo:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Costo
        mtoingreso:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoIngreso
        mtocomivta:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoComiVta
        mtocomicob:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoComiCob
    lifecycleCallbacks: {  }
