Saexis:
    type: entity
    table: SAEXIS
    id:
        codprod:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: CodProd
        codubic:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: CodUbic
    fields:
        puestoi:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: PuestoI
        existen:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Existen
        exunidad:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: ExUnidad
        cantped:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: CantPed
        unidped:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: UnidPed
        cantcom:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: CantCom
        unidcom:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: UnidCom
    lifecycleCallbacks: {  }
