Saimec:
    type: entity
    table: SAIMEC
    id:
        codmeca:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: CodMeca
            generator:
                strategy: IDENTITY
    fields:
        imagen:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: Imagen
    lifecycleCallbacks: {  }
