Saipacxc:
    type: entity
    table: SAIPACXC
    id:
        nroppal:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            id: true
            column: NroPpal
        nrounico:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: NroUnico
    fields:
        tipopag:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: TipoPag
        codpago:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: CodPago
        monto:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Monto
        descrip:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Descrip
        impuesto:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Impuesto
        retenct:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: RetencT
        codsucu:
            type: string
            nullable: false
            length: 5
            fixed: false
            default: '00000'
            column: CodSucu
    lifecycleCallbacks: {  }
