Saiprv:
    type: entity
    table: SAIPRV
    id:
        codprov:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: CodProv
            generator:
                strategy: IDENTITY
    fields:
        imagen:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: Imagen
    lifecycleCallbacks: {  }
