Saiteo:
    type: entity
    table: SAITEO
    id:
        numerod:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: NumeroD
        nrounico:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: NroUnico
        coditem:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: CodItem
    fields:
        tipoofe:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: TipoOfe
        medida:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: Medida
        monto:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Monto
        comision:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Comision
        desde:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Desde
        hasta:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Hasta
    lifecycleCallbacks: {  }
