Saitemcom:
    type: entity
    table: SAITEMCOM
    id:
        tipocom:
            type: string
            nullable: false
            length: 1
            fixed: false
            id: true
            column: TipoCom
        numerod:
            type: string
            nullable: false
            length: 20
            fixed: false
            id: true
            column: NumeroD
        codprov:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: CodProv
        nrolinea:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            id: true
            column: NroLinea
    fields:
        otipo:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: OTipo
        onumero:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: ONumero
        status:
            type: string
            nullable: true
            length: 2
            fixed: false
            column: Status
        coditem:
            type: string
            nullable: true
            length: 15
            fixed: false
            column: CodItem
        codubic:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: CodUbic
        descrip1:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Descrip1
        descrip2:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Descrip2
        descrip3:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Descrip3
        descrip4:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Descrip4
        descrip5:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Descrip5
        descrip6:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Descrip6
        descrip7:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Descrip7
        descrip8:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Descrip8
        descrip9:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Descrip9
        descrip10:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Descrip10
        refere:
            type: string
            nullable: true
            length: 15
            fixed: false
            column: Refere
        signo:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: Signo
        tara:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Tara
        cantidad:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: Cantidad
        cantidado:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: CantidadO
        existantu:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: ExistAntU
        existant:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: ExistAnt
        faltante:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Faltante
        cantidadc:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: CantidadC
        cantidadu:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: CantidadU
        cantidada:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: CantidadA
        cantidadua:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: CantidadUA
        costo:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: Costo
        totalitem:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: TotalItem
        precio1:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: Precio1
        precio2:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: Precio2
        preciou2:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: PrecioU2
        precio3:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: Precio3
        preciou3:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: PrecioU3
        preciou:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: PrecioU
        precio:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: Precio
        descto:
            type: decimal
            nullable: true
            precision: 28
            scale: 5
            default: '0'
            column: Descto
        nrounicol:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: NroUnicoL
        nrolote:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: NroLote
        fechae:
            type: datetime
            nullable: true
            column: FechaE
        fechal:
            type: datetime
            nullable: true
            column: FechaL
        fechav:
            type: datetime
            nullable: true
            column: FechaV
        esserv:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: EsServ
        esunid:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: EsUnid
        esfreep:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: EsFreeP
        espesa:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: EsPesa
        esexento:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: EsExento
        usaserv:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: UsaServ
        deslote:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: DEsLote
        desseri:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: DEsSeri
        codsucu:
            type: string
            nullable: false
            length: 5
            fixed: false
            default: '00000'
            column: CodSucu
        nrolineac:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: NroLineaC
    lifecycleCallbacks: {  }
