Saiven:
    type: entity
    table: SAIVEN
    id:
        codvend:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: CodVend
            generator:
                strategy: IDENTITY
    fields:
        imagen:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: Imagen
    lifecycleCallbacks: {  }
