Sajoin:
    type: entity
    table: SAJOIN
    uniqueConstraints:
        table1table2_idx:
            columns:
                - tablename1
                - tablename2
    id:
        tablename1:
            type: string
            nullable: false
            length: 60
            fixed: false
            id: true
        tablename2:
            type: string
            nullable: false
            length: 60
            fixed: false
            id: true
    fields:
        jointype:
            type: string
            nullable: true
            length: 60
            fixed: false
        fieldnames1:
            type: string
            nullable: true
            length: 255
            fixed: false
        operators:
            type: string
            nullable: true
            length: 60
            fixed: false
        fieldnames2:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
