Saplani:
    type: entity
    table: SAPLANI
    id:
        numerod:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: NumeroD
            generator:
                strategy: IDENTITY
    fields:
        codclie:
            type: string
            nullable: false
            length: 15
            fixed: false
            column: CodClie
        nroppal:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: NroPpal
        fechae:
            type: datetime
            nullable: true
            column: FechaE
        fechav:
            type: datetime
            nullable: true
            column: FechaV
        codsucu:
            type: string
            nullable: true
            length: 5
            fixed: false
            column: CodSucu
        codesta:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: CodEsta
        codusua:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: CodUsua
        codoper:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: CodOper
        codvend:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: CodVend
        autori:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Autori
        respon:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: Respon
        notas1:
            type: string
            nullable: true
            length: 60
            fixed: false
            column: Notas1
        notas2:
            type: string
            nullable: true
            length: 60
            fixed: false
            column: Notas2
        notas3:
            type: string
            nullable: true
            length: 60
            fixed: false
            column: Notas3
        notas4:
            type: string
            nullable: true
            length: 60
            fixed: false
            column: Notas4
        notas5:
            type: string
            nullable: true
            length: 60
            fixed: false
            column: Notas5
        notas6:
            type: string
            nullable: true
            length: 60
            fixed: false
            column: Notas6
        notas7:
            type: string
            nullable: true
            length: 60
            fixed: false
            column: Notas7
        notas8:
            type: string
            nullable: true
            length: 60
            fixed: false
            column: Notas8
        notas9:
            type: string
            nullable: true
            length: 60
            fixed: false
            column: Notas9
        notas10:
            type: string
            nullable: true
            length: 60
            fixed: false
            column: Notas10
        monto:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Monto
    lifecycleCallbacks: {  }
