Sasepropi:
    type: entity
    table: SASEPROPI
    id:
        tipoopi:
            type: string
            nullable: false
            length: 1
            fixed: false
            id: true
            column: TipoOpI
        numerod:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: NumeroD
        nroserial:
            type: string
            nullable: false
            length: 40
            fixed: false
            id: true
            column: NroSerial
        nrolinea:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            id: true
            column: NroLinea
    fields:
        nrolineac:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: NroLineaC
        status:
            type: string
            nullable: true
            length: 2
            fixed: false
            column: Status
        coditem:
            type: string
            nullable: true
            length: 15
            fixed: false
            column: CodItem
        codubic:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: CodUbic
        esconsig:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
            column: EsConsig
        codsucu:
            type: string
            nullable: false
            length: 5
            fixed: false
            default: '00000'
            column: CodSucu
    lifecycleCallbacks: {  }
