Saseri:
    type: entity
    table: SASERI
    id:
        codprod:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: CodProd
        codubic:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: CodUbic
        nroserial:
            type: string
            nullable: false
            length: 40
            fixed: false
            id: true
            column: NroSerial
    lifecycleCallbacks: {  }
