Sasericon:
    type: entity
    table: SASERICON
    id:
        codprod:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: CodProd
        codubic:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: CodUbic
        nroserial:
            type: string
            nullable: false
            length: 40
            fixed: false
            id: true
            column: NroSerial
    fields:
        nroregi:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: NroRegi
    lifecycleCallbacks: {  }
