Sasnnotif:
    type: entity
    table: SASNNOTIF
    id:
        notifyid:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            id: true
            column: NotifyId
        userid:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            id: true
            column: UserId
    fields:
        codusua:
            type: string
            nullable: false
            length: 10
            fixed: false
            column: CodUsua
        tipoverif:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: TipoVerif
        monto:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Monto
    lifecycleCallbacks: {  }
