Sataxvta:
    type: entity
    table: SATAXVTA
    id:
        tipofac:
            type: string
            nullable: false
            length: 1
            fixed: false
            id: true
            column: TipoFac
        numerod:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: NumeroD
        codtaxs:
            type: string
            nullable: false
            length: 5
            fixed: false
            id: true
            column: CodTaxs
    fields:
        monto:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Monto
        mtotax:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoTax
        tgravable:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: TGravable
        codsucu:
            type: string
            nullable: false
            length: 5
            fixed: false
            default: '00000'
            column: CodSucu
    lifecycleCallbacks: {  }
