Sataxcom:
    type: entity
    table: SATAXCOM
    id:
        tipocom:
            type: string
            nullable: false
            length: 1
            fixed: false
            id: true
            column: TipoCom
        numerod:
            type: string
            nullable: false
            length: 20
            fixed: false
            id: true
            column: NumeroD
        codprov:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: CodProv
        codtaxs:
            type: string
            nullable: false
            length: 5
            fixed: false
            id: true
            column: CodTaxs
    fields:
        monto:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Monto
        mtotax:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoTax
        tgravable:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: TGravable
        codsucu:
            type: string
            nullable: false
            length: 5
            fixed: false
            default: '00000'
            column: CodSucu
    lifecycleCallbacks: {  }
