Sataxitc:
    type: entity
    table: SATAXITC
    indexes:
        SATAXITC_IX1:
            columns:
                - CodItem
                - CodTaxs
    id:
        tipocom:
            type: string
            nullable: false
            length: 1
            fixed: false
            id: true
            column: TipoCom
        codprov:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: CodProv
        numerod:
            type: string
            nullable: false
            length: 20
            fixed: false
            id: true
            column: NumeroD
        nrolinea:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            id: true
            column: NroLinea
        codtaxs:
            type: string
            nullable: false
            length: 5
            fixed: false
            id: true
            column: CodTaxs
    fields:
        coditem:
            type: string
            nullable: true
            length: 15
            fixed: false
            column: CodItem
        monto:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Monto
        tgravable:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: TGravable
        mtotax:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoTax
        codsucu:
            type: string
            nullable: false
            length: 5
            fixed: false
            default: '00000'
            column: CodSucu
        nrolineac:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: NroLineaC
    lifecycleCallbacks: {  }
