Satmpchq:
    type: entity
    table: SATMPCHQ
    id:
        nrounico:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: NroUnico
            generator:
                strategy: IDENTITY
    fields:
        monto:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Monto
        descrip:
            type: string
            nullable: true
            length: 100
            fixed: false
            column: Descrip
        fechae:
            type: datetime
            nullable: true
            column: FechaE
        codsucu:
            type: string
            nullable: false
            length: 5
            fixed: false
            default: '00000'
            column: CodSucu
    lifecycleCallbacks: {  }
