Sbdesa:
    type: entity
    table: SBDESA
    id:
        iori:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            id: true
            column: IOri
        descripcion:
            type: string
            nullable: false
            length: 40
            fixed: false
            id: true
            column: Descripcion
    fields:
        fechauu:
            type: datetime
            nullable: false
            column: FechaUU
    lifecycleCallbacks: {  }
