Sbdopf:
    type: entity
    table: SBDOPF
    indexes:
        SBDOPF_IX1:
            columns:
                - CodOpFr
    id:
        nrounico:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: NroUnico
            generator:
                strategy: IDENTITY
    fields:
        codopfr:
            type: string
            nullable: false
            length: 30
            fixed: false
            column: CodOpFr
        codcta:
            type: string
            nullable: true
            length: 30
            fixed: false
            column: CodCta
        descripcion:
            type: string
            nullable: false
            length: 60
            fixed: false
            column: Descripcion
        codcencto:
            type: string
            nullable: true
            length: 30
            fixed: false
            column: CodCenCto
        codtercero:
            type: string
            nullable: true
            length: 30
            fixed: false
            column: CodTercero
        monto:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Monto
        monto2:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Monto2
        comentario:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: Comentario
        comentario1:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: Comentario1
        comentario2:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: Comentario2
    lifecycleCallbacks: {  }
