Sbfdcrep:
    type: entity
    table: SBFDCREP
    id:
        nrounico:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: NroUnico
            generator:
                strategy: IDENTITY
    fields:
        grupo:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: Grupo
        titgrp:
            type: string
            nullable: false
            length: 70
            fixed: false
            column: TitGrp
        tipoope:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: TipoOpe
        titulo:
            type: string
            nullable: false
            length: 70
            fixed: false
            column: Titulo
        monto:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: Monto
        mtodb:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoDb
        mtocr:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: MtoCr
    lifecycleCallbacks: {  }
