Sbopctas:
    type: entity
    table: SBOPCTAS
    id:
        codprov:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: CodProv
        nroopago:
            type: string
            nullable: false
            length: 15
            fixed: false
            id: true
            column: NroOPago
        nroilb:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            id: true
            column: NroILB
        nrolinea:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            id: true
            column: NroLinea
    fields:
        estado:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: Estado
        sdata:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: SData
        fdata:
            type: decimal
            nullable: false
            precision: 28
            scale: 4
            default: '0'
            column: FData
    lifecycleCallbacks: {  }
